a=23
b=2.7
c=1+2j
d=True
e="python"
cars=["mahindra","tata","toyota",15]
values=("thar","ktm","bmw")
numbers={1,2,4,3,2,4,7}
fset=frozenset({1,2,3,9,9,7,2})
employee={"name":"abhishek","role":"analyst","gender":"male"}
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(cars))
print(type(values))
print(type(numbers))
print(type(fset))
print(type(employee))